[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000

[rpc_endpoints]
injective_testnet = "https://k8s.testnet.json-rpc.injective.network/"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
